version: 2

models:
  - name: smart_nft_trader
    columns:
      - name: address
        tests:
          - unique
  - name: smart_nft_holder
    columns:
      - name: address
        tests:
          - unique
  - name: smart_nft_sweeper
    columns:
      - name: address
        tests:
          - unique
  - name: smart_nft_minter
    columns:
      - name: address
        tests:
          - unique
  - name: smart_nft_golden_dog_minter
    columns:
      - name: address
        tests:
          - unique
