version: 2

models:
  - name: opensea_trader
    columns:
      - name: address
        tests:
          - unique
  - name: legendary_nft_trader
    columns:
      - name: address
        tests:
          - unique
  - name: epic_nft_trader
    columns:
      - name: address
        tests:
          - unique
  - name: rare_nft_trader
    columns:
      - name: address
        tests:
          - unique
  - name: uncommon_nft_trader
    columns:
      - name: address
        tests:
          - unique      
  - name: diversified_nft_holder
    columns:
      - name: address
        tests:
          - unique      
  - name: blue_chip_nft_holder
    columns:
      - name: address
        tests:
          - unique      
